openapi: 3.2.0
info:
  title: MedDRA API EUS SBX Download API
  description: Web API to access MedDRA Data
  contact:
    name: Web Admin
    url: http://www.meddra.org/
    email: wadmin@meddra.org
  version: '1'
security:
- oauth2:
  - meddraapi
tags:
- name: Download
paths:
  /api/downld/{lang}/{ver}/{file}/{format}:
    get:
      tags:
      - Download
      summary: Returns Term objects for Downloads and Files
      parameters:
      - name: lang
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
      - name: ver
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
      - name: file
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
      - name: format
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
      responses:
        '200':
          description: Success
        200 type=1:
          description: List of historyRDTO
        200 type=10:
          description: historyDTO
        400 v1:
          description: Failed Model Validation
        400 v2:
          description: Language/Version Does Not exist
        400 v3:
          description: Insufficient Authorization
        400 v4:
          description: Invalid Input
        '401':
          description: Unauthorized Access
        '409':
          description: Data not available
        '429':
          description: The throttling limit on this API has been exceeded.  Please review the MedDRA API documentation on throttling limits.
        '500':
          description: Internal Server Error
      operationId: getApiDownldByLangByVerByFileByFormat
      x-operation-id-source: derived
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://mid.meddra.org/connect/authorize
          scopes:
            meddraapi: Meddra API - full access
